# -*- coding: utf-8 -*-
"""Ethereum and FEDformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOHgw1_u3EzPgYXlbUNl_5O9maVbFV-t

# Завантаження бібліотек
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/MAZiqing/FEDformer.git
# %cd FEDformer

!pip install einops pandas scikit-image scikit-learn scipy statsmodels sympy matplotlib yfinance pywavelets

!pip install ydata-profiling

!pip install optuna

"""# Аналіз даних"""

import pandas as pd

file_path = "/content/ETHUSD_1h_Binance.csv"
df = pd.read_csv(file_path)

df.head(), df.info()

df.columns = df.columns.str.lower()

rename_map = {
    'open time':'date',
    'timestamp':'date',
    'open':'Open',
    'high':'High',
    'low':'Low',
    'close':'Close',
    'volume':'Volume'
}

df = df.rename(columns=rename_map)

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df_filtered = df[(df['date'] >= "2021-01-01") & (df['date'] <= "2023-12-31")]
print(len(df), "→", len(df_filtered))

df_filtered = df_filtered.sort_values("date").reset_index(drop=True)

df_filtered.head(), df_filtered.info()

df = df_filtered

drop_cols = ['quote_volume','close time','trades','taker_volume','symbol','ignore','quote asset volume','number of trades','taker buy base asset volume','taker buy quote asset volume']

df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')

df['Returns'] = df['Close'].pct_change()
df = df.dropna()

output_path = "/content/ETH_clean_hourly.csv"
df.to_csv(output_path, index=False)

print("Dataset saved as:", output_path)
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# 2. Перевірка структури
print("Перші 5 рядків:")
print(df.head())
print("\nІнформація про датасет:")
print(df.info())
print("\nСтатистичний опис:")
print(df.describe())

# 3. Перевірка пропусків
print("\nКількість пропусків у кожній колонці:")
print(df.isnull().sum())

# 4. Перетворення дати у datetime
df['date'] = pd.to_datetime(df['date'])

# 5. Візуалізація ціни закриття
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Close'], label='Close Price')
plt.title('ETH Close Price Over Time')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

# 6. Розклад тренду і сезонності (приклад для денних даних з періодом 365)
result = seasonal_decompose(df['Close'], model='multiplicative', period=365)
result.plot()
plt.show()

# 7. Автокореляція і часткова автокореляція
plot_acf(df['Close'].dropna(), lags=50)
plot_pacf(df['Close'].dropna(), lags=50)
plt.show()

# 8. Візуалізація пропусків
sns.heatmap(df.isnull(), cbar=False)
plt.title('Пропуски у даних')
plt.show()

# 9. Кореляція між ознаками
corr = df[['Open','High','Low','Close','Volume']].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Кореляція між ознаками')
plt.show()

# 10. Аналіз добових доходностей (returns)
df['Returns'] = df['Close'].pct_change()
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Returns'])
plt.title('Daily Returns')
plt.show()

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Створення папки для графіків
os.makedirs('plots', exist_ok=True)
df['date'] = pd.to_datetime(df['date'])

# 1. Візуалізація ціни закриття
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Close'], label='Close Price')
plt.title("Динаміка ціни закриття Ethereum")
plt.xlabel('Дата')
plt.ylabel('Ціна (USD)')
plt.legend()
plt.savefig('plots/close_price.png')
plt.close()

# 2. Розклад тренду і сезонності
result = seasonal_decompose(df['Close'], model='multiplicative', period=365)
fig = result.plot()
fig.set_size_inches(14, 10)
fig.savefig('plots/seasonal_decompose.png')
plt.close(fig)

# 3. Автокореляція
fig, ax = plt.subplots(2,1, figsize=(14,10))
plot_acf(df['Close'].dropna(), lags=50, ax=ax[0])
plot_pacf(df['Close'].dropna(), lags=50, ax=ax[1])
fig.savefig('plots/acf_pacf.png')
plt.close(fig)

# 4. Візуалізація пропусків
plt.figure(figsize=(14,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title('Missing Data Heatmap')
plt.savefig('plots/missing_data.png')
plt.close()

df = df.dropna().reset_index(drop=True)


# 5. Кореляція
plt.figure(figsize=(8,6))
sns.heatmap(df[['Open','High','Low','Close','Volume']].corr(), annot=True, cmap='coolwarm')
plt.savefig('plots/correlation.png')
plt.close()

# 6. Добові доходності
df['Returns'] = df['Close'].pct_change()
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Returns'])
plt.title("Щоденні зміни дохідності")
plt.savefig('plots/daily_returns.png')
plt.close()

print("Візуалізації збережено в папці 'plots/'")

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Crypto Data Profiling Report")
profile.to_file("crypto_data_report.html")

"""# Запуск Optuna"""

!python optuna_fedformer.py

"""# Тренування з найкращими параметрами"""

import json
import subprocess

# === 1. Завантажуємо збережені найкращі параметри ===
with open("/content/FEDformer/results/best_params.json", "r") as f:
    best_params = json.load(f)

print("Loaded best params:")
print(best_params)

import os
os.chdir("/content/FEDformer")
print(os.getcwd())

# === 2. Формуємо команду так само, як ти запускала вручну ===
cmd = f"""
python run_custom.py \
--is_training 1 \
--task_id ETH \
--model FEDformer \
--version Fourier \
--mode_select random \
--modes {best_params['modes']} \
--seq_len {best_params['seq_len']} \
--label_len {best_params['label_len']} \
--pred_len {best_params['pred_len']} \
--batch_size {best_params['batch_size']} \
--train_epochs 30 \
--d_model {best_params['d_model']} \
--learning_rate {best_params['learning_rate']} \
--dropout {best_params['dropout']} \
--use_gpu True \
--data custom \
--root_path /content/ \
--data_path ETH_clean_hourly.csv \
--features M \
--target Close \
--freq h \
--do_predict

"""

print("\n🚀 Running training command:")
print(cmd)

# === 3. Запуск ===
result = subprocess.run(cmd, shell=True, text=True, capture_output=True)

print("\n📌 OUTPUT:")
print(result.stdout)

print("\n⚠️ ERRORS (if any):")
print(result.stderr)

import pandas as pd

re = pd.read_csv("ETH_optuna_log.csv")
valid_df = re[df["value"] != float("inf")]

import subprocess

for i, row in valid_df.iterrows():
    cmd = f"""
    python run_custom.py \
    --seq_len {row['seq_len']} \
    --label_len {row['label_len']} \
    --pred_len {row['pred_len']} \
    --modes {row['modes']} \
    --d_model {row['d_model']} \
    --batch_size {row['batch_size']} \
    --learning_rate {row['learning_rate']} \
    --dropout {row['dropout']} \
    --train_epochs 50 \
    --task_id trial_{row['trial_number']}
    """
    print(f"🚀 Training model {row['trial_number']}...")
    subprocess.run(cmd, shell=True)

import os
import glob
import numpy as np
import matplotlib.pyplot as plt

base_path = "./results/"
target_index = 0  # якщо Close інша фіча — скажи

folders = sorted(glob.glob(os.path.join(base_path, "trial_*")))

print(f"Знайдено {len(folders)} моделей.\n")

for folder in folders:
    model_name = os.path.basename(folder)

    pred_file = os.path.join(folder, "pred.npy")
    true_file = os.path.join(folder, "true.npy")
    metrics_file = os.path.join(folder, "metrics.npy")  # нове

    if not (os.path.exists(pred_file) and os.path.exists(true_file)):
        print(f"⚠️ Пропущено {model_name}: немає pred.npy або true.npy")
        continue

    pred = np.load(pred_file)
    true = np.load(true_file)

    # Завантажуємо метрики, якщо існують
    if os.path.exists(metrics_file):
        metrics = np.load(metrics_file)

        # Якщо формат [MAE, MSE, RMSE, ...]
        if len(metrics) >= 3:
            MAE, MSE, RMSE, MAPE = metrics[:4]
        else:
            MAE = MSE = RMSE = None
    else:
        MAE = MSE = RMSE = None

    print(f"{model_name} → pred shape: {pred.shape}, true shape: {true.shape}")

    # ===== Витягуємо останній прогноз =====
    pred_fixed = pred[-1, :, target_index]
    true_fixed = true[-1, :, target_index]

    # Вирівнюємо довжину
    min_len = min(len(pred_fixed), len(true_fixed))
    pred_fixed = pred_fixed[:min_len]
    true_fixed = true_fixed[:min_len]

    # ===== Побудова графіка =====
    plt.figure(figsize=(12,6))
    plt.plot(true_fixed, label="Реальні значення", color="black")
    plt.plot(pred_fixed, label="Прогнозовані значення", color="blue")
    plt.title("Прогноз FEDformer: ETH")
    plt.xlabel("Часові кроки")
    plt.ylabel("Ціна")
    plt.legend()
    plt.grid()

    # ===== Додавання тексту метрик під графік =====
    if MAE is not None:
        text = f"MAE: {MAE:.4f}   |   MSE: {MSE:.4f}   |   RMSE: {RMSE:.4f} |   MAPE: {MAPE:.4f}"
    else:
        text = "Метрики не знайдено"

    plt.text(
        0.5, -0.15, text,
        ha='center', va='center',
        transform=plt.gca().transAxes,
        fontsize=11
    )

    plt.show()
    print(f"MAE: {MAE}   |   MSE: {MSE}   |   RMSE: {RMSE} |   MAPE: {MAPE:.4f}")

    print(f"✔️ Побудовано графік + метрики для {model_name}\n")

import numpy as np
import matplotlib.pyplot as plt

true = np.load("/content/FEDformer/results/ETH_FEDformer_random_modes8_custom_ftM_sl96_ll48_pl24_dm256_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_exp_0/true.npy")
pred = np.load("/content/FEDformer/results/ETH_FEDformer_random_modes8_custom_ftM_sl96_ll48_pl24_dm256_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_exp_0/pred.npy")

print("pred shape:", pred.shape)
print("true shape:", true.shape)

plt.figure(figsize=(12,6))
plt.plot(true[0,:,0], label='True', color='black')
plt.plot(pred[0,:,0], label='Predicted', color='blue')
plt.title("FEDformer Forecast on ETH-USD")
plt.xlabel("Time steps")
plt.ylabel("Price")
plt.legend()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from FEDformer.utils.metrics import metric

# Приклад: MSE, MAE, RMSE
mae, mse, rmse, mape, mspe = metric(pred, true)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("MAPE:", mape)
print("MSPE:", mspe)

cmd = f"""
python run_custom.py \
  --is_training 1 \
  --task_id ETH_1h \
  --model FEDformer \
  --version Fourier \
  --mode_select random \
  --data custom \
  --root_path /content/ \
  --data_path ETH_clean_hourly.csv \
  --target Close \
  --freq h \
  --seq_len 336 \
  --label_len 96 \
  --pred_len 24 \
  --e_layers 3 \
  --d_layers 1 \
  --d_model 512 \
  --d_ff 1024 \
  --n_heads 8 \
  --batch_size 32 \
  --learning_rate 0.0005 \
  --dropout 0.05 \
  --train_epochs 80 \
  --patience 8 \
  --use_gpu True
"""

result = subprocess.run(cmd, shell=True, text=True, capture_output=True)

print("\n📌 OUTPUT:")
print(result.stdout)

print("\n⚠️ ERRORS (if any):")
print(result.stderr)

!zip -r fedformer_model.zip FEDformer