# -*- coding: utf-8 -*-
"""Bitcoin and FEDformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw3FWZ-HHfLoSnnQPUQbCBZleWWTd-07

# Завантаження бібліотек
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/MAZiqing/FEDformer.git
# %cd FEDformer

!pip install einops pandas scikit-image scikit-learn scipy statsmodels sympy matplotlib yfinance pywavelets

!pip install ydata-profiling

!pip install optuna

"""# Аналіз даних"""

import pandas as pd
import numpy as np


df = pd.read_csv('/content/BTC-USD.csv')
df.rename(columns={'Date': 'date'}, inplace=True)

df.to_csv('/content/BTC-USD.csv', index=False)

print(df.info())
print(df.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

print("Перші 5 рядків:")
print(df.head())
print("\nІнформація про датасет:")
print(df.info())
print("\nСтатистичний опис:")
print(df.describe())

print("\nКількість пропусків у кожній колонці:")
print(df.isnull().sum())

df['date'] = pd.to_datetime(df['date'])

# Візуалізація ціни закриття
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Close'], label='Close Price')
plt.title("Динаміка ціни закриття Bitcoin")
plt.xlabel('Дата')
plt.ylabel('Ціна (USD)')
plt.legend()
plt.show()

# Розклад тренду і сезонності
result = seasonal_decompose(df['Close'], model='multiplicative', period=365)
result.plot()
plt.show()

# Автокореляція і часткова автокореляція
plot_acf(df['Close'].dropna(), lags=50)
plot_pacf(df['Close'].dropna(), lags=50)
plt.show()

# Візуалізація пропусків
sns.heatmap(df.isnull(), cbar=False)
plt.title('Пропуски у даних')
plt.show()

# Кореляція між ознаками
corr = df[['Open','High','Low','Close','Volume']].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Кореляція між ознаками')
plt.show()

# Аналіз добових дохідностей (returns)
df['returns'] = df['Close'].pct_change()
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['returns'])
plt.title("Щоденні зміни доходності")
plt.show()

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

os.makedirs('plots', exist_ok=True)
df['date'] = pd.to_datetime(df['date'])

# Візуалізація ціни закриття
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['Close'], label='Close Price')
plt.title("Динаміка ціни закриття Bitcoin")
plt.xlabel('Дата')
plt.ylabel('Ціна (USD)')
plt.legend()
plt.savefig('plots/close_price.png')
plt.close()

# Розклад тренду і сезонності
result = seasonal_decompose(df['Close'], model='multiplicative', period=365)
fig = result.plot()
fig.set_size_inches(14, 10)
fig.savefig('plots/seasonal_decompose.png')
plt.close(fig)

# Автокореляція
fig, ax = plt.subplots(2,1, figsize=(14,10))
plot_acf(df['Close'].dropna(), lags=50, ax=ax[0])
plot_pacf(df['Close'].dropna(), lags=50, ax=ax[1])
fig.savefig('plots/acf_pacf.png')


plt.close(fig)

# Візуалізація пропусків
plt.figure(figsize=(14,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title('Missing Data Heatmap')
plt.savefig('plots/missing_data.png')
plt.close()

# Кореляція
plt.figure(figsize=(8,6))
sns.heatmap(df[['Open','High','Low','Close','Volume']].corr(), annot=True, cmap='coolwarm')
plt.savefig('plots/correlation.png')

plt.close()

# Добові дохідності
df['returns'] = df['Close'].pct_change()
plt.figure(figsize=(14,6))
plt.plot(df['date'], df['returns'])
plt.title("Щоденні зміни дохідності")
plt.savefig('plots/daily_returns.png')
plt.close()

print("Візуалізації збережено в папці 'plots/'")

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Crypto Data Profiling Report")
profile.to_file("crypto_data_report.html")

"""# Запуск Optuna"""

!python optuna_fedformer.py

"""# Тренування з найкращими параметрами"""

import json
import subprocess

with open("/content/FEDformer/results/best_params.json", "r") as f:
    best_params = json.load(f)

print("Loaded best params:")
print(best_params)

cmd = f"""
python run_custom.py \
--is_training 1 \
--task_id BTC \
--model FEDformer \
--version Fourier \
--mode_select random \
--modes {best_params['modes']} \
--seq_len {best_params['seq_len']} \
--label_len {best_params['label_len']} \
--pred_len {best_params['pred_len']} \
--batch_size {best_params['batch_size']} \
--train_epochs {100} \
--d_model {best_params['d_model']} \
--learning_rate {best_params['learning_rate']} \
--dropout {best_params['dropout']} \
--use_gpu True \
--data custom \
--root_path /content/ \
--data_path BTC-USD.csv \
--features M \
--target Close \
--freq d \
--do_predict

"""

print("\n🚀 Running training command:")
print(cmd)

result = subprocess.run(cmd, shell=True, text=True, capture_output=True)

print("\n📌 OUTPUT:")
print(result.stdout)

print("\n⚠️ ERRORS (if any):")
print(result.stderr)

import numpy as np
import matplotlib.pyplot as plt

true_ = np.load("/content/FEDformer/results/BTC_FEDformer_random_modes64_custom_ftM_sl96_ll48_pl48_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_exp_0/true.npy")
pred_ = np.load("/content/FEDformer/results/BTC_FEDformer_random_modes64_custom_ftM_sl96_ll48_pl48_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_exp_0/pred.npy")


plt.figure(figsize=(12,6))
plt.plot(true[0,:,0], label='Реальні значення', color='black')
plt.plot(pred[0,:,0], label='Прогнозовані значення', color='blue')
plt.title("Прогноз FEDformer: BTC-USD")
plt.xlabel("Часові кроки")
plt.ylabel("Ціна")
plt.legend()
plt.show()

from FEDformer.utils.metrics import metric

mae, mse, rmse, mape, mspe = metric(pred, true)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("MAPE:", mape)

!zip -r fedformer_model.zip FEDformer